### ISSUE TITLE
feature request: support party mode

### ISSUE THREAD

**Issue by doogie2301** [Tatenshi/RandomSongPicker#1]
would it be possible to have the random button in party mode, not just solo?

**Comment by Tatenshi** [comment]
Yea, i think, that it wouldn't be that much of an effort. I will look into it, when doing the next bs version update (or earlier if I find the time for it) :)

**Comment by Tatenshi** [comment]
This is now implemented and released together with 1.22 support

**Comment by DrEvilFucker** [comment]
Can you make a build with 1.21 support also?
Or a build supporting more than one version, if that's possible.

I tried loading the latest one in 1.21 after the BMBF version warning, and nothing appeared in game. (as expected)

**Comment by Tatenshi** [comment]
As it looks, the core-mods.json will probably not be updated for 1.22. Therefore a backport to 1.21 would make sense.

However, I doubt that I will be able to do this in the next 2 weeks due to exams. At this time probably already 1.23 cores will be out. Therefore i will look then again whether a backport is still needed :)
